# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KalC.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
# Developer : Divya Sai Krishna
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KalC(object):
    def setupUi(self, KalC):
        KalC.setObjectName("KalC")
        KalC.resize(464, 524)
        font = QtGui.QFont()
        font.setPointSize(11)
        KalC.setFont(font)
        self.centralwidget = QtWidgets.QWidget(KalC)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 180, 89, 61))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 180, 89, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 180, 89, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 180, 89, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 240, 89, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 240, 89, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 240, 89, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(270, 240, 89, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 300, 89, 61))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(90, 300, 89, 61))
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(50, 430, 171, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setAutoFillBackground(False)
        self.pushButton_equal.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 180, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_div = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_div.setGeometry(QtCore.QRect(270, 400, 91, 71))
        self.pushButton_div.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_mul = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mul.setGeometry(QtCore.QRect(360, 400, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(180, 300, 89, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_subtract.setGeometry(QtCore.QRect(360, 330, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_subtract.setFont(font)
        self.pushButton_subtract.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.pushButton_subtract.setObjectName("pushButton_subtract")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(360, 260, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_per = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_per.setGeometry(QtCore.QRect(270, 330, 89, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_per.setFont(font)
        self.pushButton_per.setStyleSheet("\n"
"background-color: rgb(186, 189, 182);")
        self.pushButton_per.setObjectName("pushButton_per")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_squareroot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_squareroot.setGeometry(QtCore.QRect(0, 360, 89, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_squareroot.setFont(font)
        self.pushButton_squareroot.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.pushButton_squareroot.setObjectName("pushButton_squareroot")
        self.pushButton_square = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_square.setGeometry(QtCore.QRect(90, 360, 89, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_square.setFont(font)
        self.pushButton_square.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.pushButton_square.setObjectName("pushButton_square")
        self.pushButton_power = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_power.setGeometry(QtCore.QRect(180, 360, 89, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.pushButton_power.setObjectName("pushButton_power")
        #self.pushButton_log = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_log.setGeometry(QtCore.QRect(0, 430, 101, 41))
        #self.pushButton_log.setStyleSheet("background-color: rgb(114, 159, 207);")
        #self.pushButton_log.setObjectName("pushButton_log")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        KalC.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KalC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 22))
        self.menubar.setObjectName("menubar")
        KalC.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KalC)
        self.statusbar.setObjectName("statusbar")
        KalC.setStatusBar(self.statusbar)

        self.retranslateUi(KalC)
        self.pushButton_0.clicked.connect(self.label.show)
        self.pushButton_1.clicked.connect(self.label.show)
        QtCore.QMetaObject.connectSlotsByName(KalC)

    def retranslateUi(self, KalC):
        _translate = QtCore.QCoreApplication.translate
        KalC.setWindowTitle(_translate("KalC", "MainWindow"))
        self.pushButton_1.setText(_translate("KalC", "1"))
        self.pushButton_2.setText(_translate("KalC", "2"))
        self.pushButton_3.setText(_translate("KalC", "3"))
        self.pushButton_4.setText(_translate("KalC", "4"))
        self.pushButton_5.setText(_translate("KalC", "5"))
        self.pushButton_6.setText(_translate("KalC", "6"))
        self.pushButton_7.setText(_translate("KalC", "7"))
        self.pushButton_8.setText(_translate("KalC", "8"))
        self.pushButton_9.setText(_translate("KalC", "9"))
        self.pushButton_0.setText(_translate("KalC", "0"))
        self.pushButton_equal.setText(_translate("KalC", "="))
        self.pushButton_12.setText(_translate("KalC", "C"))
        self.pushButton_div.setText(_translate("KalC", "/"))
        self.pushButton_mul.setText(_translate("KalC", "*"))
        self.pushButton_dot.setText(_translate("KalC", "."))
        self.pushButton_subtract.setText(_translate("KalC", "-"))
        self.pushButton_add.setText(_translate("KalC", "+"))
        self.pushButton_per.setText(_translate("KalC", "%"))
        self.textEdit.setHtml(_translate("KalC", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#c17d11;\">KalC</span></p></body></html>"))
        self.pushButton_squareroot.setText(_translate("KalC", "√x"))
        self.pushButton_square.setText(_translate("KalC", " x²"))
        self.pushButton_power.setText(_translate("KalC", "X^Y"))
        #self.pushButton_log.setText(_translate("KalC", "log"))

        self.pushButton_subtract.clicked.connect(self.action_minus)
        self.pushButton_equal.clicked.connect(self.action_equal)
        self.pushButton_0.clicked.connect(self.action0)
        self.pushButton_1.clicked.connect(self.action1)
        self.pushButton_2.clicked.connect(self.action2)
        self.pushButton_3.clicked.connect(self.action3)
        self.pushButton_4.clicked.connect(self.action4)
        self.pushButton_5.clicked.connect(self.action5)
        self.pushButton_6.clicked.connect(self.action6)
        self.pushButton_7.clicked.connect(self.action7)
        self.pushButton_8.clicked.connect(self.action8)
        self.pushButton_9.clicked.connect(self.action9)
        self.pushButton_div.clicked.connect(self.action_div)
        self.pushButton_mul.clicked.connect(self.action_mul)
        self.pushButton_add.clicked.connect(self.action_plus)
        self.pushButton_dot.clicked.connect(self.action_point)
        self.pushButton_12.clicked.connect(self.action_clear)
        #self.pushButton_log.clicked.connect(self.action_log)
        self.pushButton_square.clicked.connect(self.action_square)
        self.pushButton_power.clicked.connect(self.action_power)
        #p.clicked.connect(self.action_del)

    def action_equal(self):

            # get the label text
            equation = self.label.text()

            try:
                # getting the ans
                ans = eval(equation)

                # setting text to the label
                self.label.setText(str(ans))

            except:
                # setting text to the label
                self.label.setText("Wrong Input")

    def action_plus(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + " + ")

    def action_minus(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + " - ")

    def action_div(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + " / ")

    def action_mul(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + " * ")

    def action_point(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + ".")

    def action0(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "0")

    def action1(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "1")

    def action2(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "2")

    def action3(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "3")

    def action4(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "4")

    def action5(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "5")

    def action6(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "6")

    def action7(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "7")

    def action8(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "8")

    def action9(self):
            # appending label text
            text = self.label.text()
            self.label.setText(text + "9")

    def action_clear(self):
            # clearing the label text
            self.label.setText("")

    def action_del(self):
            # clearing a single digit
            text = self.label.text()
            print(text[:len(text) - 1])
            self.label.setText(text[:len(text) - 1])


    def action_percentage(self):
        text = self.label.text()
        self.label.setText(text + " % ")

    def action_square(self):
        text = self.label.text()
        a=(text + " * " + text)
        self.label.setText(a)

    def action_squareroot(self):
        text=self.label.text()
        b=(sqrt(text))
        self.label.setText(b)

    def action_power(self):
        text=self.label.text()
        self.label.setText(text+" ^ ")





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KalC = QtWidgets.QMainWindow()
    ui = Ui_KalC()
    ui.setupUi(KalC)
    KalC.show()
    sys.exit(app.exec_())
